# Eksperymenty z modelami osadzania

In [43]:
import numpy as np
from sentence_transformers import SentenceTransformer

In [44]:
model = SentenceTransformer("all-MiniLM-L6-v2")

In [45]:
model.device

device(type='cuda', index=0)

In [46]:
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [47]:
chunks = [
    "### Silne i słabe\n* Słabe encje - nie może istnieć w bazie samodzielnie bez odpowiedniej instancji innej encji\n* Silne encje - nie są zależne od istnienia innych encji",
    "### Krytyka deontologii\n* Zalety\n	* porządkuje sferę moralności\n	* nadaje się do racjonalnej dyskusji\n* Jest subiektywna tam gdzie wszystkie poglądy etyczne są subiektywne\n* Nadmierny intelektualizm\n	* nadmierne przywiązanie do zasad, abstraktów, myśli\n* Niezgodność z praktyką\n	* w praktyce ludzie nie są zazwyczaj intelektualistami\n	* nie wszyscy, nie w każdej sytuacji\n* Są sytuacje, których deontologia (np. Kantyzm) nie rozstrzyga\n	* czy to powód do odrzucenia deontologii, czy do dalszych badań",
    "## Więzy integralności\nDefiniowanie dziedzin i semantycznych warunków poprawności\n* klucze\n* więzy jednoznaczności\n* integralność referencyjna\n* integralność domenowa\n* więzy zasadnicze\n",
    "Co oznacza encja w kontekście baz danych",
]

result = model.encode(chunks)
result.shape

(4, 384)

In [48]:
type(result)

numpy.ndarray

In [49]:
model.similarity(result, result)

tensor([[1.0000, 0.5807, 0.5376, 0.4937],
        [0.5807, 1.0000, 0.5899, 0.4910],
        [0.5376, 0.5899, 1.0000, 0.4230],
        [0.4937, 0.4910, 0.4230, 1.0000]])

In [50]:
model.encode("aaa")

array([-3.88445929e-02,  7.25517720e-02,  2.06604954e-02,  1.65440757e-02,
       -4.40674648e-02,  1.49559155e-02,  2.78906077e-02,  1.36636309e-02,
        1.87189654e-02,  3.79332006e-02,  3.38768004e-03, -5.17280027e-02,
       -3.84665318e-02, -1.95072882e-03,  1.17629475e-03, -1.26239704e-02,
       -4.97185811e-02, -7.73063512e-04, -1.22403480e-01, -2.45685391e-02,
        2.31547896e-02,  8.45694467e-02,  6.33285865e-02,  2.90796831e-02,
       -9.71096684e-04,  2.89301295e-02, -1.59065556e-02,  9.18349549e-02,
       -1.61652938e-02, -4.35795300e-02,  1.13760177e-02,  3.85778882e-02,
        1.37232631e-01, -1.16852717e-03,  7.87360407e-03, -2.81664301e-02,
        1.01611752e-03,  2.01388132e-02,  3.39456648e-02, -1.53300241e-02,
        2.51482930e-02, -6.36809645e-03,  3.32557745e-02,  9.49886348e-03,
        2.62351949e-02,  3.21653262e-02,  6.49666414e-02,  5.38779981e-02,
        4.23892513e-02,  9.78336483e-02,  5.67444898e-02, -8.86210203e-02,
       -2.50860397e-02,  

In [51]:
model.encode("a" * 100)

array([-6.87265322e-02,  4.82507385e-02,  3.13927121e-02, -7.53798857e-02,
       -9.21736881e-02,  5.08766584e-02,  1.16100892e-01,  2.57765111e-02,
        2.04141680e-02, -3.92670408e-02, -7.08744600e-02, -1.10817581e-01,
        3.66016943e-03, -2.87658982e-02,  2.28324719e-02, -3.81915423e-04,
       -8.90915934e-03,  3.46877240e-03, -5.04419841e-02,  1.69870798e-02,
        9.69005823e-02,  6.92923889e-02,  2.70897374e-02,  4.55789939e-02,
       -3.46712656e-02, -5.42865060e-02, -6.32960573e-02,  2.33005676e-02,
        3.01705375e-02, -3.14377211e-02, -2.67442595e-03, -3.64798643e-02,
        5.84211200e-02, -3.46851274e-02, -1.07364701e-02,  6.11347053e-03,
        3.90976854e-02, -4.34317924e-02,  2.90927123e-02,  2.36951727e-02,
        8.37317109e-03, -3.88545394e-02,  1.59350820e-02,  4.94118268e-03,
       -2.77548674e-02, -7.25570470e-02, -1.23109641e-02, -4.52513136e-02,
        1.09268412e-01, -2.57237237e-02,  2.29543336e-02, -3.98068428e-02,
       -2.85903234e-02, -

In [27]:
model.encode("a" * 100)

array([-6.87265322e-02,  4.82507385e-02,  3.13927121e-02, -7.53798857e-02,
       -9.21736881e-02,  5.08766584e-02,  1.16100892e-01,  2.57765111e-02,
        2.04141680e-02, -3.92670408e-02, -7.08744600e-02, -1.10817581e-01,
        3.66016943e-03, -2.87658982e-02,  2.28324719e-02, -3.81915423e-04,
       -8.90915934e-03,  3.46877240e-03, -5.04419841e-02,  1.69870798e-02,
        9.69005823e-02,  6.92923889e-02,  2.70897374e-02,  4.55789939e-02,
       -3.46712656e-02, -5.42865060e-02, -6.32960573e-02,  2.33005676e-02,
        3.01705375e-02, -3.14377211e-02, -2.67442595e-03, -3.64798643e-02,
        5.84211200e-02, -3.46851274e-02, -1.07364701e-02,  6.11347053e-03,
        3.90976854e-02, -4.34317924e-02,  2.90927123e-02,  2.36951727e-02,
        8.37317109e-03, -3.88545394e-02,  1.59350820e-02,  4.94118268e-03,
       -2.77548674e-02, -7.25570470e-02, -1.23109641e-02, -4.52513136e-02,
        1.09268412e-01, -2.57237237e-02,  2.29543336e-02, -3.98068428e-02,
       -2.85903234e-02, -

## Modele są ograniczone co do liczby tokenów

* Dłuższy chyba(?) jest przycinany
* Maksymalna długość dotyczy liczby tokenów
* Metoda tokenizacji jest zależna od modelu

In [22]:
model.max_seq_length

256

In [23]:
model.tokenizer

BertTokenizerFast(name_or_path='sentence-transformers/all-MiniLM-L6-v2', vocab_size=30522, model_max_length=256, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [53]:
text = chunks[1]
len(text)

500

In [57]:
model.tokenize(text)["input_ids"].shape[0]

500

In [60]:
different_len_embeddings = [
    model.encode(text[:i])
    for i in range(1, len(text))
]

for i, emb in enumerate(different_len_embeddings[1:], start=1):
    prev_embedding = different_len_embeddings[i-1]
    is_the_same = np.allclose(emb, prev_embedding)
    number_of_tokens = model.tokenize(text[:i])["input_ids"].shape[0]
    if is_the_same:
        print(f"takie samo dla długości {i} i {i+1} (liczba tokenow to {number_of_tokens})")

takie samo dla długości 3 i 4 (liczba tokenow to 3)
takie samo dla długości 11 i 12 (liczba tokenow to 11)
takie samo dla długości 23 i 24 (liczba tokenow to 23)
takie samo dla długości 25 i 26 (liczba tokenow to 25)
takie samo dla długości 32 i 33 (liczba tokenow to 32)
takie samo dla długości 33 i 34 (liczba tokenow to 33)
takie samo dla długości 35 i 36 (liczba tokenow to 35)
takie samo dla długości 46 i 47 (liczba tokenow to 46)
takie samo dla długości 52 i 53 (liczba tokenow to 52)
takie samo dla długości 63 i 64 (liczba tokenow to 63)
takie samo dla długości 64 i 65 (liczba tokenow to 64)
takie samo dla długości 66 i 67 (liczba tokenow to 66)
takie samo dla długości 73 i 74 (liczba tokenow to 73)
takie samo dla długości 77 i 78 (liczba tokenow to 77)
takie samo dla długości 80 i 81 (liczba tokenow to 80)
takie samo dla długości 92 i 93 (liczba tokenow to 92)
takie samo dla długości 101 i 102 (liczba tokenow to 101)
takie samo dla długości 103 i 104 (liczba tokenow to 103)
takie s

In [61]:
model.max_seq_length

256

Wygląda na to, że dla języka polskiego, tokenizer tego modelu generuje 1 token na 1 znak